insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3130,75, 'Rosella', 'f', 'Jefferson St.,Riverside', 'Burks', 'U39288448');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3297,33, 'Damien', 'm', '9th, at Terrace plc', 'Avila', 'U13198786');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3547,47, 'Robin', 'm', '220 hobo Av.,Phila, PA,', 'Olsen', 'U51607510');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1538,43, 'Edgar', 'm', 'Repici,120 Jefferson St.,Riverside, NJ', 'Moises', 'U82804203');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2941,70, 'Heath', 'm', 'Jefferson St.,Riverside', 'Brian', 'U14885833');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2401,23, 'Elvin', 'm', '9th, at Terrace plc', 'Claude', 'U45468730');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2070,51, 'Edmund', 'm', '220 hobo Av.,Phila, PA,', 'Mosley', 'U55520577');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2561,23, 'Antoine', 'm', 'Repici,120 Jefferson St.,Riverside, NJ', 'Derek', 'U17379620');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1625,33, 'Callie', 'f', 'Jefferson St.,Riverside', 'Hawkins', 'U37302778');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1307,13, 'Andrea', 'f', '9th, at Terrace plc', 'Pate', 'U17879789');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2342,33, 'Liz', 'f', '220 hobo Av.,Phila, PA,', 'Austin', 'U52858303');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2755,77, 'Reba', 'f', 'Repici,120 Jefferson St.,Riverside, NJ', 'Kendrick', 'U57184004');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (4150,42, 'Angelina', 'f', 'Jefferson St.,Riverside', 'Sims', 'U90889624');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3544,16, 'Kimberly', 'f', '9th, at Terrace plc', 'Mullins', 'U90685904');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2096,13, 'Lloyd', 'm', '220 hobo Av.,Phila, PA,', 'Chuck', 'U65389635');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1089,57, 'Ladonna', 'f', 'Repici,120 Jefferson St.,Riverside, NJ', 'Payne', 'U70315168');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2948,38, 'Johnathan', 'm', 'Jefferson St.,Riverside', 'Baxter', 'U78706156');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (4539,38, 'Gilbert', 'm', '9th, at Terrace plc', 'Weiss', 'U23590938');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2811,78, 'Florence', 'f', '220 hobo Av.,Phila, PA,', 'Deirdre', 'U48482550');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (4580,42, 'Toby', 'm', 'Repici,120 Jefferson St.,Riverside, NJ', 'Fernando', 'U94834372');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2895,74, 'Patrica', 'f', 'Jefferson St.,Riverside', 'Garrison', 'U64763428');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2254,13, 'Leila', 'f', '9th, at Terrace plc', 'Effie', 'U63047438');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2389,61, 'Rose', 'f', '220 hobo Av.,Phila, PA,', 'Buckley', 'U46913868');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1699,79, 'Kathie', 'f', 'Repici,120 Jefferson St.,Riverside, NJ', 'Stanton', 'U29562021');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1567,10, 'Shannon', 'f', 'Jefferson St.,Riverside', 'Banks', 'U96462926');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3066,80, 'Cleo', 'f', '9th, at Terrace plc', 'Barnes', 'U62451485');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2426,45, 'Nellie', 'f', '220 hobo Av.,Phila, PA,', 'Brady', 'U53769251');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2217,53, 'Ruben', 'm', 'Repici,120 Jefferson St.,Riverside, NJ', 'Katheryn', 'U17765328');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1968,19, 'Dianne', 'f', 'Jefferson St.,Riverside', 'Michael', 'U59726536');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3012,71, 'Adam', 'm', '9th, at Terrace plc', 'Grant', 'U79889902');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (1824,65, 'Kurtis', 'm', '220 hobo Av.,Phila, PA,', 'Head', 'U64695146');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3929,75, 'Jami', 'm', 'Repici,120 Jefferson St.,Riverside, NJ', 'Berger', 'U60422549');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2682,75, 'Jaime', 'm', 'Jefferson St.,Riverside', 'Earline', 'U87478018');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3112,37, 'Summer', 'f', '9th, at Terrace plc', 'Evelyn', 'U60340191');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2303,43, 'Sam', 'm', '220 hobo Av.,Phila, PA,', 'Quentin', 'U78043275');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3903,50, 'Ann', 'f', 'Repici,120 Jefferson St.,Riverside, NJ', 'Dunlap', 'U29273946');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3095,58, 'Rich', 'm', 'Jefferson St.,Riverside', 'Shields', 'U98164645');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2383,35, 'Winnie', 'f', '9th, at Terrace plc', 'Page', 'U96219657');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (2146,27, 'Ezra', 'm', '220 hobo Av.,Phila, PA,', 'Sparks', 'U45331028');
insert into people (id, age, first_name, gender, home_address, last_name, passport_id) VALUES (3958,29, 'Elba', 'f', 'Repici,120 Jefferson St.,Riverside, NJ', 'Kaufman', 'U76856406');
